import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import SignUpDialog from '@/components/my-component/SignUpDialog';
import SignInDialog from '@/components/my-component/SignInDialog';
import LogOut from '@/components/my-component/LogOut';
import { getUser } from '@/lib/user';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex flex-col gap-12 px-24 py-8">
          <div className="flex justify-between">
            <div className="text-2xl font-extrabold">VoiceNow</div>
            {user ? (
              <div className="flex gap-4 items-center">
                <p>{user.email}</p>
                <LogOut />
              </div>
            ) : (
              <div className="flex gap-4 items-center">
                <SignInDialog />
                <SignUpDialog />
              </div>
            )}
          </div>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
